on: 
  push:
  workflow_dispatch:
  schedule:
    - cron: '15 3 1 * *'  # <https://crontab.guru/#45_16_*_*_0> 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Erlang
        uses: erlef/setup-beam@v1
        with:
          otp-version: '26'
          rebar3-version: '3.16.1'

      - run: ./run_tests.sh
